# Generated by Django 5.0 on 2024-05-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='feedback_text',
            field=models.TextField(blank=True),
        ),
    ]
